# Generated by Django 5.1.2 on 2024-10-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nbaapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_cap",
                    models.DecimalField(
                        decimal_places=2, default=109140000, max_digits=12
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Global Settings",
            },
        ),
    ]
