# Generated by Django 5.1.2 on 2024-10-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nbaapp", "0002_globalsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="salary_cap",
            field=models.DecimalField(
                decimal_places=2, default=188931000, max_digits=12
            ),
        ),
    ]
